export type Industry =
  | 'restaurant' | 'beauty' | 'it' | 'retail'
  | 'medical' | 'legal' | 'education' | 'construction'
  | 'finance' | 'creative' | 'event' | 'other'

export type LogoStyle =
  | 'modern' | 'elegant' | 'warm' | 'professional' | 'playful'

export type Plan = 'free' | 'standard' | 'premium'

export type FontType = 'gothic' | 'mincho' | 'maru-gothic' | 'calligraphy'

export interface WorksItem {
  id: string
  brandName: string
  industry: Industry
  industryLabel: string
  style: LogoStyle
  styleLabel: string
  plan: Plan
  planLabel: string
  fontType: FontType
  colors: string[]
  imageUrl: string
  imageAlt: string
  width: number
  height: number
  createPageUrl: string
}

export const WORKS_DATA: WorksItem[] = [
  {
    id: 'rest-001',
    brandName: '麺屋 煌',
    industry: 'restaurant',
    industryLabel: '飲食店',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#C41E3A', '#1A1A1A', '#F5F0E8'],
    imageUrl: '/images/works/rest-001.webp',
    imageAlt: '飲食店「麺屋 煌」のロゴ。角ゴシック体、朱赤と黒のモダンなデザイン',
    width: 800,
    height: 600,
    createPageUrl: '/create?industry=restaurant&style=modern'
  },
  {
    id: 'beauty-001',
    brandName: 'Lumière',
    industry: 'beauty',
    industryLabel: '美容・サロン',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#D4AF37', '#2C2C2C', '#FAF7F0'],
    imageUrl: '/images/works/beauty-001.webp',
    imageAlt: '美容院「Lumière」のロゴ。明朝体、ゴールドと黒のエレガントなデザイン',
    width: 800,
    height: 500,
    createPageUrl: '/create?industry=beauty&style=elegant'
  },
  {
    id: 'it-001',
    brandName: 'TechNova',
    industry: 'it',
    industryLabel: 'IT・Web',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#0066CC', '#003366', '#FFFFFF'],
    imageUrl: '/images/works/it-001.webp',
    imageAlt: 'IT企業「TechNova」のロゴ。角ゴシック体、青と深青のモダンなデザイン',
    width: 800,
    height: 400,
    createPageUrl: '/create?industry=it&style=modern'
  },
  {
    id: 'retail-001',
    brandName: '花日和',
    industry: 'retail',
    industryLabel: '小売・EC',
    style: 'warm',
    styleLabel: '温もり',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'maru-gothic',
    colors: ['#FF9999', '#FF6666', '#FFF5F5'],
    imageUrl: '/images/works/retail-001.webp',
    imageAlt: '小花屋「花日和」のロゴ。丸ゴシック体、ピンクと白の温もりあるデザイン',
    width: 800,
    height: 550,
    createPageUrl: '/create?industry=retail&style=warm'
  },
  {
    id: 'medical-001',
    brandName: '健 Clinic',
    industry: 'medical',
    industryLabel: '医療・健康',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#2E8B57', '#1A5A36', '#F0FFF0'],
    imageUrl: '/images/works/medical-001.webp',
    imageAlt: '診療所「健 Clinic」のロゴ。角ゴシック体、緑のプロフェッショナルなデザイン',
    width: 800,
    height: 450,
    createPageUrl: '/create?industry=medical&style=professional'
  },
  {
    id: 'legal-001',
    brandName: 'さくら法律',
    industry: 'legal',
    industryLabel: '士業・法律',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#2C2C2C', '#D4AF37', '#FAFAFA'],
    imageUrl: '/images/works/legal-001.webp',
    imageAlt: '士業事務所「さくら法律」のロゴ。明朝体、黒とゴールドのエレガントなデザイン',
    width: 800,
    height: 480,
    createPageUrl: '/create?industry=legal&style=elegant'
  },
  {
    id: 'education-001',
    brandName: '未来学園',
    industry: 'education',
    industryLabel: '教育・学習',
    style: 'warm',
    styleLabel: '温もり',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'maru-gothic',
    colors: ['#FFB347', '#FF8C00', '#FFF8E7'],
    imageUrl: '/images/works/education-001.webp',
    imageAlt: 'ソコン「未来学園」のロゴ。丸ゴシック体、オレンジの温もりあるデザイン',
    width: 800,
    height: 520,
    createPageUrl: '/create?industry=education&style=warm'
  },
  {
    id: 'construction-001',
    brandName: '建創',
    industry: 'construction',
    industryLabel: '建設・不動産',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#1A3A2A', '#2D5A3D', '#E8F5E9'],
    imageUrl: '/images/works/construction-001.webp',
    imageAlt: '建設会社「建創」のロゴ。角ゴシック体、緑のプロフェッショナルなデザイン',
    width: 800,
    height: 420,
    createPageUrl: '/create?industry=construction&style=professional'
  },
  {
    id: 'finance-001',
    brandName: 'FP相談室',
    industry: 'finance',
    industryLabel: '金融・保険',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#003366', '#006699', '#F5F9FF'],
    imageUrl: '/images/works/finance-001.webp',
    imageAlt: 'FP事務所「FP相談室」のロゴ。角ゴシック体、青の信頼感のあるデザイン',
    width: 800,
    height: 460,
    createPageUrl: '/create?industry=finance&style=professional'
  },
  {
    id: 'creative-001',
    brandName: 'Artive',
    industry: 'creative',
    industryLabel: 'クリエイティブ',
    style: 'playful',
    styleLabel: 'ポップ・楽しい',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'calligraphy',
    colors: ['#FF6B6B', '#4ECDC4', '#FFE66D'],
    imageUrl: '/images/works/creative-001.webp',
    imageAlt: 'クリエイティブスタジオ「Artive」のロゴ。書体遊び心のあるポップなデザイン',
    width: 800,
    height: 500,
    createPageUrl: '/create?industry=creative&style=playful'
  },
  {
    id: 'event-001',
    brandName: 'Happy Wedding',
    industry: 'event',
    industryLabel: 'イベント・婚礼',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#D4AF37', '#FFFAFA', '#F5F5F5'],
    imageUrl: '/images/works/event-001.webp',
    imageAlt: '婚礼プランナー「Happy Wedding」のロゴ。明朝体、ゴールドのエレガントなデザイン',
    width: 800,
    height: 540,
    createPageUrl: '/create?industry=event&style=elegant'
  },
  {
    id: 'restaurant-002',
    brandName: '串かつ げんこつ',
    industry: 'restaurant',
    industryLabel: '飲食店',
    style: 'playful',
    styleLabel: 'ポップ・楽しい',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#FF4444', '#1A1A1A', '#FFFACD'],
    imageUrl: '/images/works/restaurant-002.webp',
    imageAlt: '串かつ店「げんこつ」のロゴ。角ゴシック体、赤と黒のポップなデザイン',
    width: 800,
    height: 580,
    createPageUrl: '/create?industry=restaurant&style=playful'
  },
  {
    id: 'beauty-002',
    brandName: '香りの花園',
    industry: 'beauty',
    industryLabel: '美容・サロン',
    style: 'warm',
    styleLabel: '温もり',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'mincho',
    colors: ['#DDA0DD', '#BA55D3', '#FFF0F5'],
    imageUrl: '/images/works/beauty-002.webp',
    imageAlt: '美容院「香りの花園」のロゴ。明朝体、パープルの温もりあるデザイン',
    width: 800,
    height: 490,
    createPageUrl: '/create?industry=beauty&style=warm'
  },
  {
    id: 'it-002',
    brandName: 'Webソリューション',
    industry: 'it',
    industryLabel: 'IT・Web',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#333333', '#007AFF', '#FFFFFF'],
    imageUrl: '/images/works/it-002.webp',
    imageAlt: 'Web制作会社「Webソリューション」のロゴ。角ゴシック体、グレーのプロフェッショナルなデザイン',
    width: 800,
    height: 440,
    createPageUrl: '/create?industry=it&style=professional'
  },
  {
    id: 'retail-002',
    brandName: '器と生活',
    industry: 'retail',
    industryLabel: '小売・EC',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#8B4513', '#D2691E', '#FFFAF0'],
    imageUrl: '/images/works/retail-002.webp',
    imageAlt: '器和店「器と生活」のロゴ。明朝体、茶のエレガントなデザイン',
    width: 800,
    height: 560,
    createPageUrl: '/create?industry=retail&style=elegant'
  },
  {
    id: 'medical-002',
    brandName: '歯科 clinic 美白',
    industry: 'medical',
    industryLabel: '医療・健康',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#00CED1', '#008B8B', '#E0FFFF'],
    imageUrl: '/images/works/medical-002.webp',
    imageAlt: '歯科 clinic「美白」のロゴ。角ゴシック体、ティールブルーのモダンなデザイン',
    width: 800,
    height: 470,
    createPageUrl: '/create?industry=medical&style=modern'
  },
  {
    id: 'legal-002',
    brandName: '、行政書士',
    industry: 'legal',
    industryLabel: '士業・法律',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#1A1A2E', '#16213E', '#E8E8E8'],
    imageUrl: '/images/works/legal-002.webp',
    imageAlt: '書士事務所「、行政書士」のロゴ。角ゴシック体、藏青の信頼感のあるデザイン',
    width: 800,
    height: 510,
    createPageUrl: '/create?industry=legal&style=professional'
  },
  {
    id: 'education-002',
    brandName: '英語学園',
    industry: 'education',
    industryLabel: '教育・学習',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#4169E1', '#000080', '#F0F8FF'],
    imageUrl: '/images/works/education-002.webp',
    imageAlt: '英語学校「英語学園」のロゴ。角ゴシック体、王朝蓝のモダンなデザイン',
    width: 800,
    height: 530,
    createPageUrl: '/create?industry=education&style=modern'
  },
  {
    id: 'construction-002',
    brandName: '住宅工匠',
    industry: 'construction',
    industryLabel: '建設・不動産',
    style: 'warm',
    styleLabel: '温もり',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'maru-gothic',
    colors: ['#8B7355', '#D2B48C', '#FFFAF0'],
    imageUrl: '/images/works/construction-002.webp',
    imageAlt: '住宅会社「住宅工匠」のロゴ。丸ゴシック体、茶の温もりあるデザイン',
    width: 800,
    height: 490,
    createPageUrl: '/create?industry=construction&style=warm'
  },
  {
    id: 'finance-002',
    brandName: '資産管理',
    industry: 'finance',
    industryLabel: '金融・保険',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#000000', '#C0C0C0', '#FFFFFF'],
    imageUrl: '/images/works/finance-002.webp',
    imageAlt: '資産管理会社「資産管理」のロゴ。明朝体、銀と黒的优雅设计',
    width: 800,
    height: 520,
    createPageUrl: '/create?industry=finance&style=elegant'
  },
  {
    id: 'creative-002',
    brandName: 'デザインスタジオ',
    industry: 'creative',
    industryLabel: 'クリエイティブ',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#FF1493', '#00CED1', '#1A1A1A'],
    imageUrl: '/images/works/creative-002.webp',
    imageAlt: 'デザインスタジオ「デザインスタジオ」のロゴ。角ゴシック体、ピンクと水色的现代设计',
    width: 800,
    height: 480,
    createPageUrl: '/create?industry=creative&style=modern'
  },
  {
    id: 'event-002',
    brandName: '企画会社',
    industry: 'event',
    industryLabel: 'イベント・婚礼',
    style: 'playful',
    styleLabel: 'ポップ・楽しい',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'maru-gothic',
    colors: ['#FF69B4', '#FFD700', '#98FB98'],
    imageUrl: '/images/works/event-002.webp',
    imageAlt: '企画会社「企画会社」のロゴ。丸ゴシック体、レインボーカラー的活泼设计',
    width: 800,
    height: 550,
    createPageUrl: '/create?industry=event&style=playful'
  },
  {
    id: 'other-001',
    brandName: '動物病院',
    industry: 'other',
    industryLabel: 'その他',
    style: 'warm',
    styleLabel: '温もり',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'maru-gothic',
    colors: ['#87CEEB', '#4682B4', '#FFFACD'],
    imageUrl: '/images/works/other-001.webp',
    imageAlt: '動物病院「動物病院」のロゴ。丸ゴシック体、スカイブルー的温馨设计',
    width: 800,
    height: 500,
    createPageUrl: '/create?industry=other&style=warm'
  },
  {
    id: 'restaurant-003',
    brandName: 'ラーメン 明月',
    industry: 'restaurant',
    industryLabel: '飲食店',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#FFD700', '#B8860B', '#2C2C2C'],
    imageUrl: '/images/works/restaurant-003.webp',
    imageAlt: 'ラーメン店「ラーメン 明月」のロゴ。角ゴシック体、ゴールド的现代设计',
    width: 800,
    height: 570,
    createPageUrl: '/create?industry=restaurant&style=modern'
  },
  {
    id: 'beauty-003',
    brandName: 'ネイル沙龙',
    industry: 'beauty',
    industryLabel: '美容・サロン',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#FFB6C1', '#FF69B4', '#FFFFFF'],
    imageUrl: '/images/works/beauty-003.webp',
    imageAlt: 'ネイル沙龙「ネイル沙龙」のロゴ。明朝体、粉红色的优雅设计',
    width: 800,
    height: 510,
    createPageUrl: '/create?industry=beauty&style=elegant'
  },
  {
    id: 'it-003',
    brandName: 'アプリ開発',
    industry: 'it',
    industryLabel: 'IT・Web',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#00FF7F', '#228B22', '#1A1A1A'],
    imageUrl: '/images/works/it-003.webp',
    imageAlt: 'アプリ開発会社「アプリ開発」のロゴ。角ゴシック体、緑と黒的现代设计',
    width: 800,
    height: 430,
    createPageUrl: '/create?industry=it&style=modern'
  },
  {
    id: 'retail-003',
    brandName: '时尚ブティック',
    industry: 'retail',
    industryLabel: '小売・EC',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#000000', '#808080', '#FFFFFF'],
    imageUrl: '/images/works/retail-003.webp',
    imageAlt: '时尚ブティック「时尚ブティック」のロゴ。明朝体、黒とグレー的简约优雅设计',
    width: 800,
    height: 540,
    createPageUrl: '/create?industry=retail&style=elegant'
  },
  {
    id: 'medical-003',
    brandName: '整体院',
    industry: 'medical',
    industryLabel: '医療・健康',
    style: 'warm',
    styleLabel: '温もり',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'maru-gothic',
    colors: ['#9ACD32', '#6B8E23', '#F5FFFA'],
    imageUrl: '/images/works/medical-003.webp',
    imageAlt: '整体院「整体院」のロゴ。丸ゴシック体、黄緑的温馨设计',
    width: 800,
    height: 490,
    createPageUrl: '/create?industry=medical&style=warm'
  },
  {
    id: 'legal-003',
    brandName: '司法代書',
    industry: 'legal',
    industryLabel: '士業・法律',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#191970', '#4169E1', '#F0F8FF'],
    imageUrl: '/images/works/legal-003.webp',
    imageAlt: '司法代書事務所「司法代書」のロゴ。明朝体、藏青与蓝的优雅设计',
    width: 800,
    height: 530,
    createPageUrl: '/create?industry=legal&style=elegant'
  },
  {
    id: 'education-003',
    brandName: '音楽教室',
    industry: 'education',
    industryLabel: '教育・学習',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'mincho',
    colors: ['#4B0082', '#9370DB', '#FFFAF0'],
    imageUrl: '/images/works/education-003.webp',
    imageAlt: '音楽教室「音楽教室」のロゴ。明朝体、パープル的优雅设计',
    width: 800,
    height: 500,
    createPageUrl: '/create?industry=education&style=elegant'
  },
  {
    id: 'construction-003',
    brandName: '不動産',
    industry: 'construction',
    industryLabel: '建設・不動産',
    style: 'modern',
    styleLabel: 'モダン',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#2F4F4F', '#708090', '#F5F5F5'],
    imageUrl: '/images/works/construction-003.webp',
    imageAlt: '不動産会社「不動産」のロゴ。角ゴシック体、スレートグレー的现代设计',
    width: 800,
    height: 460,
    createPageUrl: '/create?industry=construction&style=modern'
  },
  {
    id: 'finance-003',
    brandName: '保険事務所',
    industry: 'finance',
    industryLabel: '金融・保険',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#006400', '#228B22', '#F0FFF0'],
    imageUrl: '/images/works/finance-003.webp',
    imageAlt: '保険会社「保険事務所」のロゴ。角ゴシック体、緑的专业设计',
    width: 800,
    height: 480,
    createPageUrl: '/create?industry=finance&style=professional'
  },
  {
    id: 'creative-003',
    brandName: '写真スタジオ',
    industry: 'creative',
    industryLabel: 'クリエイティブ',
    style: 'elegant',
    styleLabel: 'エレガント',
    plan: 'premium',
    planLabel: 'プレミアム',
    fontType: 'mincho',
    colors: ['#2C2C2C', '#696969', '#FFFAF0'],
    imageUrl: '/images/works/creative-003.webp',
    imageAlt: '写真スタジオ「写真スタジオ」のロゴ。明朝体、黒とグレー的优雅设计',
    width: 800,
    height: 520,
    createPageUrl: '/create?industry=creative&style=elegant'
  },
  {
    id: 'event-003',
    brandName: '司会者',
    industry: 'event',
    industryLabel: 'イベント・婚礼',
    style: 'professional',
    styleLabel: 'プロフェッショナル',
    plan: 'standard',
    planLabel: 'スタンダード',
    fontType: 'gothic',
    colors: ['#DC143C', '#FFD700', '#1A1A1A'],
    imageUrl: '/images/works/event-003.webp',
    imageAlt: 'ウェディング司会「司会者」のロゴ。角ゴシック体、赤と金的专业设计',
    width: 800,
    height: 550,
    createPageUrl: '/create?industry=event&style=professional'
  }
]

export const INDUSTRY_OPTIONS: { value: Industry | 'all'; label: string }[] = [
  { value: 'all', label: 'すべて' },
  { value: 'restaurant', label: '飲食店' },
  { value: 'beauty', label: '美容・ Salon' },
  { value: 'it', label: 'IT・Web' },
  { value: 'retail', label: '小売・EC' },
  { value: 'medical', label: '医療・健康' },
  { value: 'legal', label: '士業・法律' },
  { value: 'education', label: '教育・学習' },
  { value: 'construction', label: '建設・不動産' },
  { value: 'finance', label: '金融・保険' },
  { value: 'creative', label: 'クリエイティブ' },
  { value: 'event', label: 'イベント・婚礼' },
  { value: 'other', label: 'その他' },
]

export const STYLE_OPTIONS: { value: LogoStyle | 'all'; label: string }[] = [
  { value: 'all', label: 'すべて' },
  { value: 'modern', label: 'モダン' },
  { value: 'elegant', label: 'エラーガント' },
  { value: 'warm', label: '温もり' },
  { value: 'professional', label: 'プロフェッショナル' },
  { value: 'playful', label: 'ポップ・楽しい' },
]
